# Generated by Django 2.2.dev20181115144358 on 2018-12-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
