# Generated by Django 2.2.dev20181115144358 on 2018-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_auto_20181212_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
