# Generated by Django 2.2.dev20181115144358 on 2018-12-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_auto_20181212_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicio',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
